spring.application.name=user-service
jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://localhost:5432/planificationDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082

admin.email=${ADMIN_EMAIL:admin@demo.com}
admin.password=${ADMIN_PASSWORD:admin123}